### ISSUE TITLE
プラグイン："popular-qiita-items" 人気の記事をトゥートする

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-API#58]
## 提案

BOT に Qiitaの「人気の投稿 beta」をトゥートさせたい。
https://qiita.com/popular-items

### プラグイン側
- RSSフィード（ https://qiita.com/popular-items/feed ）を取得
- 上位 n 件を前回保存ぶんと比較
- 差分を返す

### プロセス側

- プラグインからデータを受け取りトゥートするだけ（定例処理＋公開トゥート？）

まだ完成形でないものの 新着Qiita記事 の動きが割と良い感じなのですが、新しいものだけでなく、もう少し既存の記事にもスポットを当てたトゥートが欲しいな、と。

「人気の投稿」であれば、Qiita ユーザーの流行というか動向がわかるし、公開トゥートしても悪くないかな、と。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗  2017/11/15 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

**Comment by KEINOS** [comment]
単純に n 件だけだと
n < m として

**Comment by KEINOS** [comment]
あいやクローズしちゃった。

**Comment by hidao80** [comment]
∑👍（ﾟ∀ﾟ👍）ｲｶｽ!!

**Comment by KEINOS** [comment]
👍 

実装用に専用のブランチを作成しました。これにコミットして行きます。
https://github.com/Qithub-BOT/scripts/tree/add-tooting_popular_qiita_items-20171115-2300

**Comment by KEINOS** [comment]
PR #67 でプラグインを作成しました。プラグインなので、トゥートはできないです。

https://blog.keinos.com/qithub_dev/?plugin_name=popular-qiita-items&mode=debug

で、動作を確認できます。

- ToDo:トゥート

**Comment by KEINOS** [comment]
プラグインから Qithubコマンドに名称が変更されたことにより、実装はするものとして、一旦この issue は close してもいいのではないかと思います。

問題なければ close お願いし 💪
