### ISSUE TITLE
Qithub のサーバーにインストールするプログラム言語

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-API#80]
## 提案
[Issue #79 より](https://github.com/Qithub-BOT/scripts/issues/79#issuecomment-352215922)
> golang：私がプラグイン開発に使いたいだけ。

新サーバーには以下（TL;DR）の言語を入れる方向で考えています。（いずれも最新の安定版）

各々のインストールが終わり次第クローズしたいと思いますが、他にあればコメントください。まし

## TL;DR（結論 2018/05/24 現在）

- インストール済みの一覧をリアルタイムに確認できるようにしました。

http://qithub.tk/api/version/
（将来的に要 GitHub OAuth ログインで確認できるようにします）

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。
- 関連 Issue #79

**Comment by hidao80** [comment]
👍

**Comment by hidao80** [comment]
他に思いつかないですね…😑

**Comment by KEINOS** [comment]
> 他に思いつかないですね…😑

ね。他に要望が出たら、都度インストールを検討するってことで、上からインストールして行きます。

インストールし終わったら、クローズしましょう。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
Qithub.tk のサーバーに表題のプログラム語インストールし終わりました！

クローズお願いし 💪 !

**Comment by hidao80** [comment]
お疲れ様でした！😁👍

**Comment by KEINOS** [comment]
申し訳ありません。**サーバーの再インストールをしてしまいました**。

`scripts` repo を https://api.qithub.tk に適用後、Mondorescue でサーバーの丸ごとバックアップをしようとしたところ途中の**手続きミスでファイル（おそらくコアファイル類）を壊してしまいました**、、、

Web（DocumentRoot下の）ファイル類は別途バックアップ済みだったものの、プログラム言語類は再インストールが必要です。

また、以前のこの issue クローズ時に　Mondorescue でサーバーの丸ごとバックアップしたものはあるのですが、リカバリーが上手くいきません。リカバリ時のパーティションマップが合わないのか、ブートローダーが壊れてしまい、復元できませんでした、、、

（[さくらのVPSでバックアップ方法](https://qiita.com/halpas/items/2f51d3b9954367f1587e)までは色々情報はあるのですが、リカバリまで検証した記事がない、、、あっても VM などの別環境でバックアップイメージを動かすといったものばかりです）

一晩奮闘しましたが、再構築した方が早いと判断し、クリーンインストールいたしました。

こんな時期に申し訳ありませんが、再オープンいたします。 🙇‍♀️

**Comment by hidao80** [comment]
無問題、実質的なサービス停止中だったので大事ないです。

開発言語類についても現在稼働しておらず、損害は軽微であると考えます。

いつも鯖缶、ご苦労様です🙇。ありがとうございます。

**Comment by KEINOS** [comment]
こちらこそいつもありがとうございます。
至急速やかに 決して走らず 急いで歩きながら そして早く復旧いたします。

**Comment by KEINOS** [comment]
インストール済みプログラム言語やライブラリの更新が面倒なので、リアルタイムで確認ができるようにしました。

http://qithub.tk/api/version/

サーバ内のバージョン情報公開はセキュリティ的にもセンシティブなので、本当は DEV.Qithub.tk で GitHub OAuth ログイン済み（Orgメンバー）のみ確認できるようにすべきなのですが、取り急ぎ。

問題なければ close お願いし 💪
