### ISSUE TITLE
新着Qiita記事 ハッシュタグ検索が機能しない件について

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-API#92]
## 問題

最近、Qiitadon もメンバーが増え、徐々に Mastodon に小慣れてきたユーザが増えるなか、ハッシュタグ検索をすると、ほとんどの（技術系）タグで Qithub-BOT の時報の取りまとめトゥートがヒットしてしまいます。

[インスタンス・マスター](https://qiitadon.com/@htomine/99686794029432043)からも「**技術関連のハッシュタグの検索結果を埋めちゃってるのちょっとつらい**」という苦言が出ているので、ドゲントCentOSに移管。

## 自分の案

サーバーの引っ越しもダンボールを開けていない状態ですが、ふと**公開でトゥートしてもLTLを汚さない方法**を考えつきました。

他者に対しての返信は公開であっても LTL に流れないのを利用して。

1. 時報専用のBOTアカウントを用意する
2. 従来の Qithub-BOT は上記アカウントの時報トゥートに返信する。

QithubサーバにMastodonを導入する案もあるのですが、ちょっと思うところもありペンディングになっておりますが、上記であれば割と簡単に実装できると思います。

## TL;DR（進捗・結論 2018/04/10 現在）

- [x] 過去の思い出を削除中
- [ ] BOT の稼働環境の引っ越し
- [ ] 取りまとめトゥートの廃止
- [ ] 時報トゥートと新着Qiita記事トゥートのアカウントをわける
    - [ ] 新着Qiita記事は最新の**時報トゥートに対して返信する**
- [ ] 新着Qiita記事をトゥートする際に suffix （後置詞）を加える（例： #TAG_qiita）

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
うーん？ なんとなくインスタンス・マスター様の意見と相違があるような…？🤔

> 毎時の投稿されたタグ一覧の投稿が技術関連のハッシュタグの検索結果を埋めちゃってるのちょっとつらいかなー

とおっしゃっておられているので、**LTLに限らず、Qiitadonのトゥートログに*ほとんどのハッシュタグ検索を無効化するほどの、タグだけが羅列されているトゥート*が濫造(1日24回発行)されている**のを憂慮されおられるように推察します。
Qiitaの人気タグ(ex. python)は、毎時なにがしかか投稿されていると推察され、とすると **Qiitadonログのタグ検索の先頭40件内（Mastodonで一度に検索できる最大トゥート数）の半分をほぼ確実にQithubが埋めてきて** 、Qiitadon上でpythonタグ打ってもトゥートが検索で見つかりにくいというのが「つらいかなー」なのかと。

なので、私はこの問題の本質を **「Qiitadonのトゥートを検索したいのにQiita記事情報ばかりかかってくる」** のだと考えているのですが、いかがでしょうか🤨

**Comment by KEINOS** [comment]
> Qiitadon上でpythonタグ打ってもその一般トゥートが検索で見つかりにくいというのが「つらいかなー」なのかと
>
> 「Qiitadonのトゥートを検索したいのにQiita記事情報ばかりかかってくる」 のだと考えているのですが、いかがでしょうか🤨


確かに。悲しいかな、いちユーザーとしてもわかるところです。（Qithub-BOT涙目）

「毎時の投稿されたタグ一覧の投稿」とあったので、てっきり取りまとめトゥートを指しており、該当Qiita記事への導線が機能していないのだと解釈しておりました。（実際そうですが。。。）

しかし、考えてみると、ホーム上であればフィルターをかけることができても、**ハッシュタグ検索の場合は結果にフィルターをかけられない**ので、「Qiita 記事以外で、とあるキーワード（タグ）について情報を dig したい場合」に舌打ちが聞こえてくるようです。

@hidao80 さんの [MastoFilter](https://github.com/hidao80/MastoFilter) が割と Qiitadon ユーザーから食いつきが良いのもそれを表していると思います。

## 対案

    1. 時報トゥートと新着Qiita記事トゥートのアカウントをわける（初案と同じ）
    2. 新着Qiita記事をトゥートする際に prefix もしくは suffix を加える（追加）
       例）#ui → #qiita_ui or #ui_qiita

従来の**デメリットは変わらない**のですが、若干のメリットは生まれるので**手間の割には善処感がある**と思うのですが、加えて新着 Qiita 記事をハッシュタグ検索から除外もできると思います。いかがでしょう？

## デメリット

1. タグ検索時に **prefix/suffix 付きで検索しないと新着Qiita記事は表示されない**
1. Qithub(bot)のフォロワーのホームが 新着Qiita記事トゥートで埋まる（フィルターで対処可能）

## メリット

1. タグ検索時に **prefix/suffix 付きで検索しないと新着Qiita記事は表示されない**
1. タグ検索時に**取りまとめトゥートでなく新着Qiita記事トゥートが表示される**
1. LTL 上の**トゥートが減る**（時報のみで取りまとめトゥートがなくなる）
1. Qiitadonユーザー関係なく、**どの新着Qiita記事トゥートもブースト可能**になる

**Comment by KEINOS** [comment]
って、ポイントは同じ話をしていますね。 (>_<)

**Comment by hidao80** [comment]
## 対案A

1. 取りまとめトゥートの廃止（上記対案と同じ）
2. 時報トゥートと新着Qiita記事トゥートのアカウントをわける（初案と同じ）
3. 新着Qiita記事をトゥートする際に prefix もしくは suffix を加える（← 新規追加）
   例）#ui → #qiita_ui or #ui_qiita
4. 【NEW!】新着記事トゥートを非収載とし、時報トゥートに新着記事トゥートの検索方法（prefix or postfix or ather）のアナウンスをさせる。

4.によって、**qithub-BOTのタグフィード化**が可能なのではないかと考えています→任意のタグの新着情報だけをタグ検索で**アクティブに**拾うことができる

**Comment by hidao80** [comment]
非収載のトゥート、たしかにタグ検索でかかりませんでした…（自分のトゥートなのに！）

閑話休題。

1. の`#TAG_qiita`に賛成です。
でもこれ、**後置詞にみえます。**TAGが対象の名詞で、それに`_qiita`を後置しているイメージです。（参考：<https://www.google.co.jp/search?q=前置詞とは>）

さておき、対象タグが前に来ていて、タグ検索で前方一致時にノイズになりにくいというのも好感です。また、検索候補に紛れ込みやすいというのも👍w

**Comment by KEINOS** [comment]
> 1. の#TAG_qiitaに賛成です。
> でもこれ、後置詞にみえます。

ほんとだ！後置詞にみえます！（ってかtypoです 😳）

では、`#TAG_qiita` ということで！ 👍 

さて、今後の流れですが、まずは大きく以下の３点を行いたいと思います。

1. BOT を新サーバーで稼働させる
1. タグの後置詞（postfix・suffix）実装
1. 旧タグの削除

3 ですが、少々時間がかかるとは言うものの、やはり**すでに汚しているタグを綺麗にする必要がある**と思うので、旧スタイルのタグ（過去のトゥート）の削除中に他の事項を進め、消し終わってから、心機一転で新スタイルのタグで BOT を再稼働させたいと思います。

特に問題なければ Close お願いし 💪 

逆に何かあればコメント 4649 メカドック

**Comment by KEINOS** [comment]
> 行動順は箇条書き昇順ではないですよね？ いきなりBOTを再起動？🤔

あいや！言葉足らずでした！ってか、わかりづらくて申し訳ないです。
気持ちはその通りでございます。

1. 旧タグの削除開始（その間に以下を実行）
1. BOT を新サーバー~~で稼働させる~~に引っ越し（DEVモードで検証）
1. タグの後置詞（postfix・suffix）実装 （#TAG_qiitaスタイル）

です！まずは[トゥートの削除](94#issuecomment-380018570) をはじめましょう。

新年度の断捨離からスタートってことで！

**Comment by KEINOS** [comment]
今晩、[必殺仕事人に削除依頼をする](94#issuecomment-380018570)ので、抹殺が終わったらこの issue はクローズしましょう！

**Comment by hidao80** [comment]
サービス休止のトゥート以外のトゥートすべての削除を確認しました。

クローズし💪
