### ISSUE TITLE
Qithub-BOT の一時停止と体制の見直し

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-API#94]
## 報告

アナウンス後、本日（2018/04/09）20時に [qithub(bot)](https://qiitadon.com/@qithub) を一時停止いたします。

issue #92 の問題やサーバーの引っ越しを完結させたいのもあり、諸処の体制を整えて再出発したいと思います。

対応の概要は以下 TL;DR 参照のこと。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗・結論 2018/05/24 現在）

- 今後の新規 issue はメインリポジトリ [Qithub-ORG の issues に統一](https://github.com/Qithub-BOT/Qithub-ORG/issues)
- [x] 新サーバに BOT の引っ越し
- [x] ハッシュタグの処理 （issue #92 ）
- [x] リポジトリの整理  （issue [items #94](/Qithub-BOT/items/issues/94)）

**Comment by KEINOS** [comment]
停止のアナウンスをいたしましたー

https://qiitadon.com/@qithub/99829038434552799

**Comment by KEINOS** [comment]
> 内容がないよう！😖

うぉっと！こらまた失礼！ TL;DR 更新しました！

**Comment by hidao80** [comment]
フラッシュアイデアですが、今の間に「トゥート消すマン」に仕事してもらうのもありかも？

**Comment by KEINOS** [comment]
> 今の間に「トゥート消すマン」に仕事してもらうのもありかも？

[ 👍まずはトゥート削除で ](92#issuecomment-380033454) 必殺仕事に依頼しましょう！

**Comment by KEINOS** [comment]
BOT の過去のトゥート削除も済んだので、TL;DR 更新しました。

問題なければ、おてすきに close お願いし 💪
